name: update_url.py
on:
  workflow_dispatch:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Prepare
        run: pip install requests beautifulsoup4
      - name: Run update_url.py
        env:
          URL_SHORTENER_API_KEY: ${{ secrets.URL_SHORTENER_API_KEY }}
        run: python update_url.py
